import { useEffect, useState } from 'react'
import { useUser } from '../context/UserContext'

export default function ProfilePage() {
  const { userId, user, updateUser, switchUser, refreshUser } = useUser()

  const [usernameInput, setUsernameInput] = useState(user?.username ?? '')
  const [usernameError, setUsernameError] = useState<string | null>(null)
  const [usernameToast, setUsernameToast] = useState(false)

  const [toggleError, setToggleError] = useState<string | null>(null)

  const [recoveryId, setRecoveryId] = useState('')
  const [recoveryUsername, setRecoveryUsername] = useState('')
  const [recoveryError, setRecoveryError] = useState<string | null>(null)
  const [recoveryToast, setRecoveryToast] = useState(false)

  useEffect(() => {
    if (user?.username) setUsernameInput(user.username)
  }, [user?.username])

  if (!user || !userId) {
    return <div className="p-6 text-center text-gray-400">Loading profile…</div>
  }

  const isAutoGenerated = user.username.startsWith('transit_')

  async function handleSaveUsername() {
    setUsernameError(null)
    try {
      await updateUser({ username: usernameInput.trim() })
      setUsernameToast(true)
      setTimeout(() => setUsernameToast(false), 2000)
    } catch (err: unknown) {
      const detail = (err as { response?: { data?: { detail?: string } } })?.response?.data?.detail
      setUsernameError(detail ?? 'Could not update username.')
    }
  }

  async function handleRecovery() {
    setRecoveryError(null)
    const id = Number(recoveryId)
    if (!Number.isInteger(id) || id <= 0) {
      setRecoveryError('Enter a valid numeric user ID.')
      return
    }
    const result = await switchUser(id, recoveryUsername.trim())
    if (result.success) {
      await refreshUser()
      setRecoveryToast(true)
      setTimeout(() => setRecoveryToast(false), 2000)
    } else if (result.error === 'mismatch') {
      setRecoveryError('Credentials do not match.')
    } else {
      setRecoveryError('User not found.')
    }
  }

  async function handleToggle(field: 'has_stroller_profile' | 'is_disabled', value: boolean) {
    setToggleError(null)
    try {
      await updateUser({ [field]: value })
    } catch {
      setToggleError('Could not save setting. Please try again.')
    }
  }

  return (
    <div className="max-w-md mx-auto p-6 flex flex-col gap-6 overflow-y-auto h-full">
      <h1 className="text-xl font-bold text-gray-800">Your Profile</h1>

      {/* User ID */}
      <div className="bg-blue-50 border border-blue-200 rounded-xl p-4">
        <p className="text-xs text-blue-500 font-medium uppercase tracking-wide">User ID</p>
        <p className="text-2xl font-bold text-blue-700 mt-1">{userId}</p>
        <p className="text-xs text-gray-500 mt-1">Note this ID and your username to recover your profile on another device.</p>
      </div>

      {/* Username edit */}
      <div className="flex flex-col gap-2">
        <label className="text-sm font-medium text-gray-700">
          Username
          {isAutoGenerated && (
            <span className="ml-2 text-xs text-amber-600 font-normal">Set a memorable name for account recovery</span>
          )}
        </label>
        <div className="flex gap-2">
          <input
            value={usernameInput}
            onChange={e => setUsernameInput(e.target.value)}
            className="flex-1 border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-blue-400"
            placeholder="Choose a username"
          />
          <button
            onClick={handleSaveUsername}
            disabled={usernameInput.trim() === user.username}
            className="px-4 py-2 rounded-lg bg-blue-600 text-white text-sm font-medium hover:bg-blue-700 disabled:opacity-40"
          >
            Save
          </button>
        </div>
        {usernameError && <p className="text-xs text-red-500">{usernameError}</p>}
        {usernameToast && <p className="text-xs text-green-600">Username updated ✓</p>}
      </div>

      {/* Email */}
      <div className="flex flex-col gap-1">
        <label className="text-sm font-medium text-gray-700">Email</label>
        <p className="text-sm text-gray-500 border border-gray-200 rounded-lg px-3 py-2 bg-gray-50">{user.email}</p>
      </div>

      {/* Accessibility toggles */}
      <div className="flex flex-col gap-3">
        <p className="text-sm font-medium text-gray-700">Accessibility settings</p>
        {([
          { key: 'has_stroller_profile' as const, label: 'I travel with a stroller' },
          { key: 'is_disabled' as const, label: 'I need wheelchair / accessibility space' },
        ]).map(({ key, label }) => (
          <label key={key} className="flex items-center justify-between cursor-pointer">
            <span className="text-sm text-gray-600">{label}</span>
            <div
              onClick={() => handleToggle(key, !user[key])}
              className={`relative w-11 h-6 rounded-full transition-colors cursor-pointer ${user[key] ? 'bg-blue-600' : 'bg-gray-300'}`}
            >
              <span
                className={`absolute top-0.5 left-0.5 w-5 h-5 bg-white rounded-full shadow transition-transform ${user[key] ? 'translate-x-5' : ''}`}
              />
            </div>
          </label>
        ))}
        {toggleError && <p className="text-xs text-red-500 mt-1">{toggleError}</p>}
      </div>

      {/* Account recovery */}
      <div className="border-t pt-5 flex flex-col gap-3">
        <p className="text-sm font-medium text-gray-700">Sign in with existing account</p>
        <p className="text-xs text-gray-500">Enter your User ID and username to switch to a saved profile.</p>
        <input
          type="number"
          value={recoveryId}
          onChange={e => setRecoveryId(e.target.value)}
          placeholder="User ID"
          className="border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-blue-400"
        />
        <input
          value={recoveryUsername}
          onChange={e => setRecoveryUsername(e.target.value)}
          placeholder="Username"
          className="border border-gray-300 rounded-lg px-3 py-2 text-sm focus:outline-none focus:border-blue-400"
        />
        <button
          onClick={handleRecovery}
          className="py-2 rounded-lg bg-gray-800 text-white text-sm font-medium hover:bg-gray-900"
        >
          Sign in
        </button>
        {recoveryError && <p className="text-xs text-red-500">{recoveryError}</p>}
        {recoveryToast && <p className="text-xs text-green-600">Signed in successfully ✓</p>}
      </div>
    </div>
  )
}
